### ISSUE TITLE
Compile error on Linux x86_64

### ISSUE THREAD

**Issue by Flupper** [calmopyrin/yapesdl#1]
YapeSDL fails to compile (GCC 7.2.1) for me after this commit (Isolated CIA emulation code )
https://github.com/calmopyrin/yapesdl/commit/0fc463e77beaded1fb60601b326f237f45a7d781

[michael@manjaro yapesdl]$ make
g++ -O3 -w -I/usr/include/SDL2 -D_REENTRANT -c 1541mem.cpp
g++ -O3 -w -I/usr/include/SDL2 -D_REENTRANT -c archdep.cpp
g++ -O3 -w -I/usr/include/SDL2 -D_REENTRANT -c cpu.cpp
g++ -O3 -w -I/usr/include/SDL2 -D_REENTRANT -c dis.cpp
g++ -O3 -w -I/usr/include/SDL2 -D_REENTRANT -c diskfs.cpp
g++ -O3 -w -I/usr/include/SDL2 -D_REENTRANT -c dos.cpp
g++ -O3 -w -I/usr/include/SDL2 -D_REENTRANT -c drive.cpp
g++ -O3 -w -I/usr/include/SDL2 -D_REENTRANT -c FdcGcr.cpp
g++ -O3 -w -I/usr/include/SDL2 -D_REENTRANT -c iec.cpp
g++ -O3 -w -I/usr/include/SDL2 -D_REENTRANT -c interface.cpp
g++ -O3 -w -I/usr/include/SDL2 -D_REENTRANT -c keyboard.cpp
g++ -O3 -w -I/usr/include/SDL2 -D_REENTRANT -c keys64.cpp
g++ -O3 -w -I/usr/include/SDL2 -D_REENTRANT -c main.cpp
g++ -O3 -w -I/usr/include/SDL2 -D_REENTRANT -c monitor.cpp
g++ -O3 -w -I/usr/include/SDL2 -D_REENTRANT -c prg.cpp
g++ -O3 -w -I/usr/include/SDL2 -D_REENTRANT -c SaveState.cpp
g++ -O3 -w -I/usr/include/SDL2 -D_REENTRANT -c serial.cpp
g++ -O3 -w -I/usr/include/SDL2 -D_REENTRANT -c Sid.cpp
g++ -O3 -w -I/usr/include/SDL2 -D_REENTRANT -c sound.cpp
g++ -O3 -w -I/usr/include/SDL2 -D_REENTRANT -c tape.cpp
g++ -O3 -w -I/usr/include/SDL2 -D_REENTRANT -c tcbm.cpp
g++ -O3 -w -I/usr/include/SDL2 -D_REENTRANT -c tedmem.cpp
g++ -O3 -w -I/usr/include/SDL2 -D_REENTRANT -c tedsound.cpp
g++ -O3 -w -I/usr/include/SDL2 -D_REENTRANT -c vic2mem.cpp
g++ -O3 -w -I/usr/include/SDL2 -D_REENTRANT -c video.cpp
g++ -O3 -w -I/usr/include/SDL2 -D_REENTRANT -o yapesdl -s 1541mem.o archdep.o cpu.o dis.o diskfs.o dos.o drive.o FdcGcr.o iec.o interface.o keyboard.o keys64.o main.o monitor.o prg.o SaveState.o serial.o Sid.o sound.o tape.o tcbm.o tedmem.o tedsound.o vic2mem.o video.o -L/usr/lib -lSDL2
vic2mem.o: In function `Vic2mem::~Vic2mem()':
vic2mem.cpp:(.text+0x288): undefined reference to `Cia::refCount'
vic2mem.o: In function `Vic2mem::Read(unsigned int)':
vic2mem.cpp:(.text+0x6fd): undefined reference to `Cia::read(unsigned int)'
vic2mem.cpp:(.text+0x75c): undefined reference to `Cia::read(unsigned int)'
vic2mem.cpp:(.text+0x8f8): undefined reference to `Cia::read(unsigned int)'
vic2mem.cpp:(.text+0x916): undefined reference to `Cia::read(unsigned int)'
vic2mem.cpp:(.text+0x9ab): undefined reference to `Cia::read(unsigned int)'
vic2mem.o: In function `non-virtual thunk to Vic2mem::~Vic2mem()':
vic2mem.cpp:(.text+0xad0): undefined reference to `Cia::refCount'
vic2mem.o: In function `Vic2mem::~Vic2mem()':
vic2mem.cpp:(.text+0xb98): undefined reference to `Cia::refCount'
vic2mem.o: In function `non-virtual thunk to Vic2mem::~Vic2mem()':
vic2mem.cpp:(.text+0xc58): undefined reference to `Cia::refCount'
vic2mem.o: In function `Vic2mem::Reset(bool)':
vic2mem.cpp:(.text+0x13c5): undefined reference to `Cia::reset()'
vic2mem.cpp:(.text+0x13d1): undefined reference to `Cia::reset()'
vic2mem.o: In function `Vic2mem::Vic2mem()':
vic2mem.cpp:(.text+0x15cc): undefined reference to `Cia::refCount'
vic2mem.cpp:(.text+0x15d5): undefined reference to `Cia::refCount'
vic2mem.cpp:(.text+0x2a10): undefined reference to `Cia::reset()'
vic2mem.cpp:(.text+0x2a1a): undefined reference to `Cia::reset()'
vic2mem.cpp:(.text+0x2d6a): undefined reference to `Cia::refCount'
vic2mem.o: In function `Vic2mem::loadromfromfile(int, char const*, unsigned int)':
vic2mem.cpp:(.text+0x38df): undefined reference to `Cia::reset()'
vic2mem.cpp:(.text+0x38eb): undefined reference to `Cia::reset()'
vic2mem.o: In function `Vic2mem::Write(unsigned int, unsigned char)':
vic2mem.cpp:(.text+0x4101): undefined reference to `Cia::write(unsigned int, unsigned char)'
vic2mem.cpp:(.text+0x48e9): undefined reference to `Cia::write(unsigned int, unsigned char)'
vic2mem.cpp:(.text+0x4a05): undefined reference to `Cia::write(unsigned int, unsigned char)'
vic2mem.o: In function `Vic2mem::readState()':
vic2mem.cpp:(.text+0x4f9e): undefined reference to `Cia::write(unsigned int, unsigned char)'
vic2mem.cpp:(.text+0x4fb4): undefined reference to `Cia::write(unsigned int, unsigned char)'
vic2mem.o:vic2mem.cpp:(.text+0x5f03): more undefined references to `Cia::write(unsigned int, unsigned char)' follow
vic2mem.o: In function `Vic2mem::ted_process(unsigned int)':
vic2mem.cpp:(.text+0x8a84): undefined reference to `Cia::countTimers()'
vic2mem.cpp:(.text+0x8a8e): undefined reference to `Cia::countTimers()'
vic2mem.cpp:(.text+0x8bf7): undefined reference to `Cia::setIRQflag(unsigned int)'
vic2mem.cpp:(.text+0xa2c3): undefined reference to `Cia::todUpdate()'
vic2mem.cpp:(.text+0xa2cd): undefined reference to `Cia::todUpdate()'
vic2mem.o: In function `Vic2mem::Read(unsigned int)':
vic2mem.cpp:(.text+0x899): undefined reference to `Cia::read(unsigned int)'
vic2mem.o: In function `Vic2mem::Write(unsigned int, unsigned char)':
vic2mem.cpp:(.text+0x409d): undefined reference to `Cia::write(unsigned int, unsigned char)'
collect2: error: ld returned 1 exit status
make: *** [Makefile:46: yape] Error 1
[michael@manjaro yapesdl]$

**Comment by calmopyrin** [comment]
Fix is coming, thanks for reporting.
