### ISSUE TITLE
Cannot switch emulator

### ISSUE THREAD

**Issue by musuruan** [calmopyrin/yapesdl#10]
I'm using Yape/SDL 0.80.1 on Fedora 40/x86_64.

When I try to switch emulator pressing LALT+L I get the following error in the terminal:
`INFO: error opening window`

And the emulator isn't switched.

**Comment by calmopyrin** [comment]
Must be an SDL issue with some window managers. In Ubuntu it works for me, in WSL it doesn't. Who knows... if you change line 837 in main.cpp to this:
`#if 0`
and recompile it should switch (without confirmation).

**Comment by calmopyrin** [comment]
Submitted a patch that circumvents this and switches the emulation mode regardless of the result of the messagebox window creation.

**Comment by musuruan** [comment]
Sorry to bother, but where can I see this patch?

**Comment by calmopyrin** [comment]
Hi, just pushed the commit to the tree
[](https://github.com/calmopyrin/yapesdl/commit/f28839b5d51c9a86bfe850b2278db06daba42709)
