### ISSUE TITLE
Using relative paths for command line argument does not work

### ISSUE THREAD

**Issue by zzarko** [calmopyrin/yapesdl#6]
yapesdl, on start, loads a configuration and sets working directory to that in the configuration. That is fine if it is started without arguments, as it resumes from where it was last time.
But, if there is an argument in the command line, it will load/autostart file ONLY if the file is in the path from where yapesdl is started. but, if I put relative path to a file, then it does not work because current directory is changed when configuration is loaded and then relative paths are wrong.
For example, if this is directory structure:
```
dir1/
     /file1.prg
     /dir2/
          /file2.prg
```
and shell is in dir1/dir2, this works:
`./yapesdl file2.prg`
but this does not:
`./yapesdl ../file1.prg`
Proposed solution: if there is a command line argument, switch working directory to its directory. In the attachment is a patch (made with git diff) that implements this solution and so far works great for me (it probably should have more checks). This will also be convenient if, for example, multi-disk game is started, as selecting next image will be in the same directory, and not somewhere from configuration file.

[patch.log](https://github.com/calmopyrin/yapesdl/files/9484122/patch.log)

**Comment by calmopyrin** [comment]
yapesdl was originally not meant to deal with the command line much (well, until recently) but the relative path is an issue that needs to be ironed out in the next commit. Thanks for your effort flagging it!

**Comment by zzarko** [comment]
Thanks for responding to me! I already had a contact with Gaia on plus4world, and I wrote that I implemented many CLI tools in the past and would gladly implement parameter parsing for yapesdl. I just need to know what effect of each option should be (setting a variable/structure member, function call, something else) and what options should be available.

**Comment by calmopyrin** [comment]
relative path related bug was fixed in one of the recent commits
