### ISSUE TITLE
Question about emscripten use

### ISSUE THREAD

**Issue by renegadeandy** [calmopyrin/yapesdl#9]
Hi! I have compiled Yape for MacOS - it's working great.

I now want to compile so I can run from a browser using emscripten, however I don't see anymore detailed guide on how to do this.

Do you have the emcc compilation string you used when you did this which you can share? It would be very much appreciated!

**Comment by calmopyrin** [comment]
Hi, glad it worked! Alas, I'm using Visual Studio with an emscripten addin, so there is not much of a script that I could share and I haven't really got around making one yet either. Maybe later...
